# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_api', '0002_auto_20170308_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='donerdetails',
            name='blood_group',
            field=models.TextField(default='A+'),
        ),
    ]
