# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_api', '0003_donerdetails_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerdetails',
            name='recently_donated',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
