# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_api', '0004_auto_20170308_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donerdetails',
            name='age',
        ),
        migrations.AddField(
            model_name='donerdetails',
            name='class_dept',
            field=models.TextField(default='S6 CS'),
        ),
        migrations.AddField(
            model_name='donerdetails',
            name='college',
            field=models.TextField(default='College of Engineering Trivandrum'),
        ),
        migrations.AddField(
            model_name='donerdetails',
            name='location',
            field=models.TextField(default='Trivandrum'),
        ),
        migrations.AddField(
            model_name='donerdetails',
            name='phone_number',
            field=models.IntegerField(default=9447206588),
        ),
    ]
