# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-10 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_api', '0005_auto_20170310_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerdetails',
            name='blood_group',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donerdetails',
            name='class_dept',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donerdetails',
            name='college',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='donerdetails',
            name='location',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donerdetails',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
