# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-11 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_api', '0009_auto_20170311_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='donerdetails',
            name='coordinates',
            field=models.TextField(default=' '),
        ),
    ]
