# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-11 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_api', '0012_auto_20170311_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerdetails',
            name='coordinates',
            field=models.TextField(default='x'),
        ),
    ]
