# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-11 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_api', '0014_auto_20170311_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donerdetails',
            name='coordinates2',
        ),
        migrations.AddField(
            model_name='donerdetails',
            name='coordinates3',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
